stages:
  - lint

linter:
  stage: lint
  image: ${CI_REGISTRY}/ict/images/alpine/ci:3.18
  cache:
    paths:
      - node_modules/
  before_script:
    - apk add --no-cache nodejs npm
  script:
    - echo "\033[1;35mInstalling dependencies...\033[0m"
    - npm ci
    - echo "\033[1;35mLinting...\033[0m"
    - npm run cilint
  artifacts:
    expire_in: 1 week
    reports:
      codequality: eslint.xml
  rules:
    - if: $CI_COMMIT_BRANCH # run on pushes
    - if: $CI_MERGE_REQUEST_ID # run on merge requests
  