include:
  - local: .gitlab/linting.yml
  - local: .gitlab/code_quality.yml
  - local: .gitlab/secret_detection.yml
  - local: .gitlab/dependency_scanning.yml
  - local: .gitlab/sast.yml
  - local: .gitlab/deployment.yml

stages:
  - lint
  - test
  - deploy