include:
  - local: .gitlab/linting.yml
  - local: .gitlab/code_quality.yml
  - local: .gitlab/secret_detection.yml
  - local: .gitlab/deployment.yml
    rules:
      - if: $PIPELINE_TYPE == "scheduled_test"
        when: never
  - local: .gitlab/dependency_scanning.yml
    rules:
      - if: $PIPELINE_TYPE == "scheduled_test"
  - local: .gitlab/sast.yml
    rules:
      - if: $PIPELINE_TYPE == "scheduled_test"

stages:
  - lint
  - test
  - deploy