.freezedeployment:
  stage: deploy
  before_script:
    - '[[ ! -z "$CI_DEPLOY_FREEZE" ]] && echo "INFRASTRUCTURE OUTAGE WINDOW" && exit 1; '
  rules:
    - if: '$CI_DEPLOY_FREEZE'
      when: manual
      allow_failure: true
    - when: on_success

deployment:
  extends: .freezedeployment
  rules:
    - if: $PIPELINE_TYPE == "scheduled_test"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: ${CI_REGISTRY}/ict/images/alpine/ci:3.18
  cache:
    paths:
      - node_modules/
  before_script:
    - apk add --no-cache nodejs npm
  script:
    - echo "\e[33mInstalling dependencies...\e[0m"
    - npm ci
    - npm install --global vercel
    - echo "\e[34m\e[4mDeploying...\e[24m\e[0m"
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
  environment:
    name: staging
    url: $VERCEL_DEPLOY_URL